attributes:
  metadata:
    group: 'network'
  asnumber:
    value: "64511"
    label: "AS Number"
    description: "AS number for BGP communications"
    weight: 20
    type: "text"
    regex:
      source: '^(?:(6553[0-5])|(655[0-2]\d)|(65[0-4]\d{2})|(6[0-4]\d{3})|([1-5]\d{4})|([1-9]\d{1,3})|([1-9]))$'
      error: "Invalid AS number"
  external_peers:
    value: "10.109.3.250"
    label: "BGP peers"
    description: "Comma separated IP addresses of BGP peers"
    weight: 40
    type: "text"
    regex:
      source: '^(?:\d|1?\d\d|2[0-4]\d|25[0-5])(?:\.(?:\d|1?\d\d|2[0-4]\d|25[0-5])){3}(?:,\s*(?:\d|1?\d\d|2[0-4]\d|25[0-5])(?:\.(?:\d|1?\d\d|2[0-4]\d|25[0-5])){3})*$'
      error: "Invalid IP address list"